// <auto-generated />
using System;
using InheirtanceMapping.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InheirtanceMapping.Migrations
{
    [DbContext(typeof(CompanyRouteG02DbContext))]
    partial class CompanyRouteG02DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InheirtanceMapping.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InheirtanceMapping.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("InheirtanceMapping.Models.Employee");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.ToTable("FullTimeEmployees", (string)null);
                });

            modelBuilder.Entity("InheirtanceMapping.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("InheirtanceMapping.Models.Employee");

                    b.Property<int>("CountOfHours")
                        .HasColumnType("int");

                    b.Property<decimal>("HourRate")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("PartTimeEmployees", (string)null);
                });

            modelBuilder.Entity("InheirtanceMapping.Models.FullTimeEmployee", b =>
                {
                    b.HasOne("InheirtanceMapping.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("InheirtanceMapping.Models.FullTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InheirtanceMapping.Models.PartTimeEmployee", b =>
                {
                    b.HasOne("InheirtanceMapping.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("InheirtanceMapping.Models.PartTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
